exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]

  - repo: local
    hooks:
      - id: migrations-check
        name: check for uncreated migrations.
        entry: python manage.py makemigrations --check --dry-run
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

      #TODO: enable this once we have working tests
      # - id: tests
      #   name: run tests
      #   entry: python manage.py test --settings=config.settings.test -n
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   require_serial: true
      #   stages: ["push"]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
