default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master, --branch, production]
      - id: check-merge-conflict
      - id: check-builtin-literals
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.288
    hooks:
      - id: ruff
        types: [python]
