networks:
  default:
    name: care
services:
  backend:
    build:
      context: /home/wednesday/care
      dockerfile: docker/DevDockerfile
    container_name: care
    depends_on:
      db:
        condition: service_started
    entrypoint:
    - bash
    - docker/docker-entrypoint.sh
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@db:5432/care
      DJANGO_DEBUG: "False"
      FACILITY_S3_BUCKET: facility-bucket
      FILE_UPLOAD_BUCKET: patient-bucket
      POSTGRES_DB: care
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: '5432'
      POSTGRES_USER: postgres
    ports:
    - published: 9000
      target: 9000
    - published: 9876
      target: 9876
    volumes:
    - /home/wednesday/care:/app:rw
  celery:
    build:
      context: /home/wednesday/care
      dockerfile: docker/DevDockerfile
    container_name: care_celery
    depends_on:
      backend:
        condition: service_started
      db:
        condition: service_started
      redis:
        condition: service_started
    entrypoint:
    - bash
    - devCelery.sh
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@db:5432/care
      DJANGO_DEBUG: "False"
      FACILITY_S3_BUCKET: facility-bucket
      FILE_UPLOAD_BUCKET: patient-bucket
      POSTGRES_DB: care
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: '5432'
      POSTGRES_USER: postgres
    volumes:
    - /home/wednesday/care:/app:rw
  db:
    container_name: care_db
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@db:5432/care
      DJANGO_DEBUG: "False"
      FACILITY_S3_BUCKET: facility-bucket
      FILE_UPLOAD_BUCKET: patient-bucket
      POSTGRES_DB: care
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: '5432'
      POSTGRES_USER: postgres
    image: postgres:latest
    restart: always
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw
  localstack:
    environment:
      AWS_DEFAULT_REGION: ap-south-1
      EDGE_PORT: '4566'
      SERVICES: s3
    image: localstack/localstack:latest
    volumes:
    - /home/wednesday/care/docker/awslocal:/docker-entrypoint-initaws.d:rw
    - /tmp/localstack:/tmp/localstack:rw
  redis:
    container_name: care_redis
    image: redis:alpine
    restart: always
version: '3.4'
volumes:
  postgres-data: {}

