version: '3.4'

services:
  db:
    env_file:
      - ./docker/.local.env

  backend:
    build:
      context: .
      dockerfile: docker/DevDockerfile
    env_file:
      - ./docker/.local.env
    volumes:
      - .:/app

  celery:
    container_name: care_celery
    build:
      context: .
      dockerfile: docker/DevDockerfile
    env_file:
      - ./docker/.local.env
    entrypoint: [ "bash", "celery_dev.sh" ]
    depends_on:
      - db
      - backend
      - redis
    volumes:
      - .:/app
