version: '3.4'

networks:
  default:
    name: care

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - ./docker/.prebuilt.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
    volumes:
      - "${TEMPDIR:-./care/media/localstack}:/var/lib/localstack"
      - "./docker/awslocal:/etc/localstack/init/ready.d/"
    ports:
      - "4566:4566"

  fidelius:
    image: khavinshankar/fidelius:v1.0
    restart: always

volumes:
  postgres-data:
  redis-data:
