version: '3.4'

services:
  backend:
    image: care_local
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    env_file:
      - ./docker/.local.env
    volumes:
      - .:/app
    entrypoint: [ "bash", "scripts/start-dev.sh" ]
    ports:
      - "9000:9000"
      - "9876:9876" #debugpy
    depends_on:
      - db
      - redis

  celery:
    image: care_local
    env_file:
      - ./docker/.local.env
    entrypoint: [ "bash", "scripts/celery-dev.sh" ]
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
