name: Lambda Deployment

on:
  pull_request:
    branches:
      - devops/lambda-changes
    paths-ignore:
      - "docs/**"
jobs:
  build-image:
    name: Build & Push Staging to container registries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:lambda-${{ github.event.pull_request.number }} -f lambda_Dockerfile .
          docker push ghcr.io/${{ github.repository }}:lambda-${{ github.event.pull_request.number }}
